apiVersion: v1
kind: Service
metadata:
  name: springboot-genai-service
spec:
  selector:
    app: springboot-genai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP